---
title: "每週一圖作業繪圖說明檔"
output: html_document
params:
  組員: ["邱詩涵"]  
  學號: ["410773056"]
---

#### 環境設定

以下為老師執行時一定會存在的環境設定
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
rm(list=ls())
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(colorspace); library(grDevices); library(shiny); library(shinyjs); library(scales)
library(tidyr); library(showtext); library(tidyverse); library(colorspace)

#font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(fig.align='center', fig.showtext=T)
```


#### 繪圖程式

```{r graph, echo=T, eval=T}
library(grDevices) # 不同顏色模型代碼的呈現及轉換
library(scales) # show_col()螢幕立即顯示顏色
library(colorspace) # 調色盤選擇及ggplot應用工具
library(shinyjs) # 支援套件
library(statebins)
#choose_palette(gui="shiny")

load("uploadgraph.Rda")

graphData$sub_2015_city_North %>% 
  ggplot() + 
  geom_point(
    aes(
      x = area, 
      y = avg_nh
    ), 
    shape = 18, 
    size = 10, 
    color = "#00BBFF", 
    alpha = 1
  ) +
  geom_point(
    data = graphData$sub_2015_city_Central, 
    aes(
      x = area, 
      y = avg_nh
    ), 
    shape = 18, 
    size = 10, 
    color = "#FF7744", 
  ) + 
  geom_point(
    data = graphData$sub_2015_city_South, 
    aes(
      x = area, 
      y = avg_nh, 
      ), 
    shape = 18, 
    size = 10, 
    color = "#FF8888",
  ) +
  geom_point(
    data = graphData$sub_2015_city_East_Islands, 
    aes(
      x = area, 
      y = avg_nh, 
      ), 
    shape = 18, 
    size = 10, 
    color = "#00AA00",
  ) + 
  theme_bw(
    base_size = 20, base_family = "",
  base_line_size = 20/22, base_rect_size = 20/22
  ) + 
  theme(
    panel.border = element_rect(fill = NA,color = "gray"), 
    panel.grid.minor = element_blank() 
  ) + 
  theme(
    axis.ticks = element_blank(), 
    axis.title = element_blank()
  ) + 
  scale_x_discrete(
    limits = c("East_Islands","South","Central","North"), 
    breaks = c("East_Islands","South","Central","North"),
    labels = c("東部\n離島","南部","中部","北部")
  ) +
  coord_flip()+
   annotate(
    "text",
    x = 4,
    y = 6.29,
    label = "宜蘭縣",
    vjust = -1.5
  ) +
  annotate(
    "text",
    x = 3,
    y = 3.39,
    label = "雲林縣",
    vjust = -1.5
  ) +
  annotate(
    "text",
    x = 2,
    y = 4.76,
    label = "屏東縣",
    vjust = -1.5
  ) +
  annotate(
    "text",
    x = 1,
    y = 8.12,
    label = "連江縣",
    vjust = -1.5
  )+
  labs(
    title = "臺灣各縣市平均每10,000位老人可使用的長照機構數量", 
    subtitle = "2015年統計資料"
  ) + 
  theme(
    plot.title = element_text(face = "bold",hjust = 0.5), 
    plot.subtitle = element_text(color = "#AAAAAA")
  ) -> graphData$sub_2015_city_final

graphData$sub_2015_city_final
  
```

#### 設計說明
說明想傳達的訊息（必要）及設計想法（非必要）。寫在***下一行。

*** 
臺灣各縣市平均每10,000位老人可使用的長照機構數量：

從圖中可發現，北部與東部離島區的數量較分散，中部及南部較集中，各地區平均數量最高的是<b>宜蘭縣</b>(6.29,北)、<b>雲林縣</b>(3.39,中)、<b>屏東縣</b>(4.76,南)、<b>連江縣</b>(8.12,東離)。


