---
title: "每週一圖作業繪圖說明檔"
output: html_document
params:
  組員: ["小明","小花"]  
  學號: ["410773818","410773293"]
---

#### 環境設定

以下為老師執行時一定會存在的環境設定
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
rm(list=ls())
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(colorspace); library(grDevices); library(shiny); library(shinyjs); library(scales);
library(tidyr); library(showtext); library(tidyverse); library(colorspace);library(sf);library(cowplot)

#font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(fig.align='center', fig.showtext=T)
```


#### 繪圖程式

```{r graph, echo=T, eval=T}
graphData <- list()
load(file = "df_politics_news.rda")
Country <-c("Sri Lanka",
        "Honkong",
        "US",
        "South Korea",
        "US",
        "Afghanistan",
        "US",
        "Iran",
        "Israel",
        "US",
        "Syria",
        "Burkina Faso",
        "Mali",
        "Niger",
        "Brazil",
        "Chile",
        "Bolivia",
        "Britain",
        "Sweden",
        "Belarus")
Event <- c("Election",
"Defiance",
"Law",
"Diplomatic",
"Diplomatic",
"Law",
"Election",
"Defiance",
"Defiance",
"Defiance",
"Defiance",
"Defiance",
"Defiance",
"Defiance",
"Environment",
"Environment",
"Environment",
"Environment",
"Environment",
"Environment"
)
politics <- data.frame(Country,Event)

graphData$politicsCategory <- politics

graphData$politicsCategory %>%
  ggplot()+
  geom_point( aes(
    x = Event,
    y = Country,
    colour = Event
  ))+
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.background = element_rect(fill = 	"#FFFAF0"),
        axis.line = element_line(colour = "#8B4513"),
        axis.ticks = element_line(colour = "#8B4513"),
        axis.text = element_text(colour = "#8B4513",)
        ) -> graphData$politicsCategory_graph




# 取出spData套件附的world data
data(world,package="spData")
world %>% st_geometry() %>%
  ggplot()+geom_sf()+geom_sf(data = df_politics_news,aes(fill = "#FF7744"))+
  theme(legend.position = "none") -> graphData$politicsNewsMap


plot_grid(graphData$politicsNewsMap, graphData$politicsCategory_graph, 
          labels = c("A", "B"),
          ncol = 1, nrow = 2)

```

#### 設計說明
說明想傳達的訊息（必要）及設計想法（非必要）。寫在***下一行。

*** 

