---
title: '001'
author: "Shihhan"
date: "2019年9月11日"
output: html_document
---

```{r basic setup, message=FALSE, echo=TRUE, eval=T}
rm(list=ls())
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(colorspace); library(grDevices); library(shiny); library(shinyjs); library(scales)
library(tidyr); library(showtext); library(tidyverse); library(colorspace);library(listviewer)

font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(fig.align='center', fig.showtext=T)
```


```{r}


```



```{r}
file.create(".Rprofile")
file.edit(".Rprofile")
```


```{r}
Sys.getenv("plotly_username")
Sys.getenv("plotly_api_key")



```


```{r}
source("https://www.dropbox.com/s/wlv1ssxqq6n4p7u/gg_hw5_004.R?dl=1", encoding = "utf-8")
```


```{r}
gg_hw5_004 %>%
  ggplotly() ->
  pltly_hw5_004


api_create(pltly_hw5_004,filename="pltly_hw5_004",fileopt="overwrite") -> Meta_pltly_hw5_004
pltly_hw5_004_v1 <- api_download_plot("1","shihhan2018")
pltly_hw5_004_v1
```


```{r}
p <- ggplot(mtcars, aes(x = wt, y = mpg)) +
   geom_point() + geom_smooth()

p
pltly_p0 <- ggplotly(p)

pltly_p0 %>% plotly_json()
```


