---
title: "每週一圖作業資料檔"
output: html_document
params:
  組員: ["李靜怡"]  
  學號: ["410773095"]
---

#### 環境設定

以下為老師執行時一定會存在的環境設定
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
rm(list=ls())
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(colorspace); library(grDevices); library(shiny); library(shinyjs); library(scales)
library(tidyr); library(showtext); library(tidyverse); library(colorspace); library(magick); library(magrittr)

#font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(fig.align='center', fig.showtext=T)
```

#### 資料處理
  
```{r data cleaning, echo=TRUE, eval=T}
## 資料讀入
library(dplyr); library(rvest); library(stringr)
source("https://www.dropbox.com/s/4tubw8e5h3cem6w/theEconomist.R?dl=1")

"https://www.economist.com/the-world-this-week/2019/11/21/politics-this-week" %>%
  get_theWorldThisWeek() -> df_politics

"https://www.economist.com/the-world-this-week/2019/11/21/business-this-week" %>%
  get_theWorldThisWeek() -> df_business

data(world,package = "spData")

## 資料整理

df_politics[11,] -> df_politics[c(18:19),]

df_politics$identities[11] %>%
  str_split(",") -> a

a[[1]] -> df_politics$identities[c(11,18,19)]

df_politics$identities %>%
  str_sub(2,-2) %>%
  str_replace("’s","") -> df_politics$identities

df_politics$identities[15] <- "United Kingdom"
df_politics$identities[c(3,6)] <- "United States"
df_politics$identities[9] <- "Israel"
df_politics$identities[12] <- "Brazil"
df_politics$identities[16] <- "Sweden"
df_politics$identities[4] <- "Republic of Korea"

world[(world$name_long %in%
  df_politics$identities),] -> df_politics_news

save(df_politics_news,
     file = "df_politics_news.rda")
```

