---
title: "每週一圖作業資料檔"
output: html_document
params:
  組員: ["彭亦楓","李靜怡","鄭喬翊","曾雨晴","邱詩涵"]  
  學號: ["410773109","","","","410773056"]
---

#### 環境設定

以下為老師執行時一定會存在的環境設定
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
rm(list=ls())
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(colorspace); library(grDevices); library(shiny); library(shinyjs); library(scales)
library(tidyr); library(showtext); library(tidyverse); library(colorspace); library(ggpubr); library(magick);
library(sf); library(rmapshaper);library(magrittr)

#font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(fig.align='center', fig.showtext=T)
```

#### 資料處理
  


```{r}
load("map.rda")
load("df_politics_news.rda")
```


```{r}
class(df_politics_news)


##1.取出"歐洲"的國家
(df_politics_news$region_un=="Europe")  

##2.把"歐洲"df 其中geom資料由polygon轉為中心點
df_politics_news[(df_politics_news$region_un=="Europe"),] %>%
  st_centroid(of_largest_polygon = T) -> df_center_Europe

##3.取出中心點的座標
df_center_Europe%>%
  st_coordinates() -> coordinates_Europe

##4.處理資料
#中心點們的座標目前為matrix，要把matrix轉為data.frame
#若最後檢查圖案發現label太擠，要先在這邊的df調整X及Y的值
#若一個地區有複數個事件，要先在這邊的df新增一筆資料，設定好第二個label的XY座標
as.data.frame(coordinates_Europe) -> df_coordinates_Europe
df_coordinates_Europe

##5.新增一變數名為`event`，底下的值是該座標對應到的事件。
df_coordinates_Europe %>%
  mutate(
    event=c("4-5","4-6","4-4")
  ) ->df_coordinates_Europe

df_coordinates_Europe


##6.畫上label(只要正確處理上面步驟4.及步驟5.，這邊完全不用動就可以生成有label的地圖)
map$Europe+
  geom_label(
    data = df_coordinates_Europe,
    aes(x=X,y=Y,label=event)
  ) -> map$Europe_label
map$Europe_label
```

```{r}
##把"Americas"df 其中geom資料由polygon轉為中心點
df_politics_news[(df_politics_news$region_un=="Americas"),] %>%
  st_centroid(of_largest_polygon = T) -> df_center_Americas

##取出中心點的座標
df_center_Americas%>%
  st_coordinates() -> coordinates_Americas

##處理資料
as.data.frame(coordinates_Americas) -> df_coordinates_Americas

df_coordinates_Americas <- rbind(df_coordinates_Americas,
                                 c(-75.2422,31.4227),
                                 c(-132.1019,39.2627),
                                 c(-126.5507,31.1718),
                                 c(-112.2900,45.5141))
df_coordinates_Americas%>%
  slice(c(-2,-4)) -> df_coordinates_Americas

df_coordinates_Americas

df_coordinates_Americas <-rbind(df_coordinates_Americas,
                                c(-79.2103,-31.0505),
                                c(-78.0729,-16.3340))

df_coordinates_Americas <- round(df_coordinates_Americas,4)

df_coordinates_Americas 
##新增`event`
df_coordinates_Americas %>%
  mutate(
    event=c("4-1","3-2","5-1","2-1","2-2","1-3","4-2","4-3")
  ) ->df_coordinates_Americas

df_coordinates_Americas
##畫上label
map$Americas +
  geom_label(
    data = df_coordinates_Americas,
    aes(x=X,y=Y,label=event)
  )  -> map$Americas_label
map$Americas_label
```



```{r}
##把"Asia"df 其中geom資料由polygon轉為中心點
df_politics_news[(df_politics_news$region_un=="Asia"),] %>%
  st_centroid(of_largest_polygon = T) -> df_center_Asia

##取出中心點的座標
df_center_Asia%>%
  st_coordinates() -> coordinates_Asia

##處理資料
as.data.frame(coordinates_Asia) -> df_coordinates_Asia
df_coordinates_Asia %>%
  slice(-1,-2,-5,-6)->df_coordinates_Asia

df_coordinates_Asia

df_coordinates_Asia <- rbind(df_coordinates_Asia,
                             c(115.0022,20.3439),
                             c(133.3009,38.5843),
                             c(85.2737,10.2738),
                             c(32.5128,39.0700),
                             c(31.2059,32.1032))

df_coordinates_Asia
##新增`event`
df_coordinates_Asia %>%
  mutate(
    event=c("5-2","1-2","1-1","2-1","3-1","1-4","1-3")
  ) ->df_coordinates_Asia

df_coordinates_Asia

##畫上label
map$Asia +
  geom_label(
    data = df_coordinates_Asia,
    aes(x=X,y=Y,label=event)
  ) -> map$Asia_label

map$Asia_label
```

```{r}

df_politics_news[7,] %>%
  st_centroid(of_largest_polygon = T) -> df_center_Faso

##取出中心點的座標
df_center_Faso%>%
  st_coordinates() -> coordinates_Faso

##處理資料
as.data.frame(coordinates_Faso) -> df_coordinates_Faso
df_coordinates_Faso$X+6 ->df_coordinates_Faso$X
df_coordinates_Faso$Y+10.5 ->df_coordinates_Faso$Y

##新增`event`
df_coordinates_Faso %>%
  mutate(
    event=c("1-5")
  ) ->df_coordinates_Faso

df_coordinates_Faso

##畫上label
map$Africa +
  geom_label(
    data = df_coordinates_Faso,
    aes(x=X,y=Y,label=event)
  ) -> map$Africa_label

map$Africa_label
```

```{r}
save(map,file = "mapWithLabel.Rda")
```










